### ISSUE TITLE
DOC | Featured implementation

### ISSUE THREAD

**Issue by louisgv** [ift-gftc/doc.ift.org#3]
### What is the use case for this additional documentation?

Here are the winners and devposts to feature:

https://cologne-trackathon.devpost.com just the winner (Sanitised fish) https://devpost.com/software/sanitized-fish

https://bali-trackathon.devpost.com/submissions 1st and 3rd.

### External relevant resources

https://github.com/louisgv/doc.ift.org/issues/22

**Comment by IFTGFTC** [comment]
dropbox https://www.dropbox.com/sh/tmxjt5v5r40r789/AAAfmtxcwgTOWq4yrhZZ2Xx7a?dl=0
